In [ ]:
# ## ✅ 문제 1. (중급 ⭐⭐⭐)

# **[계산기 프로그램 만들기]**

# ✅ 조건:

# - 사용자로부터 숫자 2개와 연산자(+, -, *, /)를 입력받는다.
# - 해당 연산을 수행하고 결과를 출력한다.
# - 0으로 나누는 경우 예외 처리한다.

# ✅ 예시 실행:

# ```
# javascript
# 복사편집
# 첫 번째 숫자를 입력하세요: 10
# 두 번째 숫자를 입력하세요: 2
# 연산자를 입력하세요 (+, -, *, /): /
# 결과: 5.0

# ```

def exitChk(chk):
    if chk == 'q' or chk == 'Q': return True
    else: return False
        

result = 0
while True:
    num1 = input('첫 번째 숫자를 입력하세요:')
    if exitChk(num1) == True:
        print('계산기를 종료합니다.')
        break
    else: num1 = int(num1)

    num2 = int(input('두 번째 숫자를 입력하세요:'))
    if exitChk(num2) == True:
        print('계산기를 종료합니다.')
        break
    else: num2 = int(num2)

    if num1 == 0 or num2 == 0:
        print('0을 입력하셨습니다. 다시 입력하세요.')
        continue

    a = input('연산자를 입력하세요 (+, -, *, /):')
    if exitChk(a) == True:
        print('계산기를 종료합니다.')
        break

    if a == '+':
        result = num1 + num2
        break
    elif a == '-':
        result = num1 - num2
        break
    elif a == '*':
        result = num1 * num2    
        break
    elif a == '/':
         result = num1 / num2
         break
    else:
        print('연산자를 잘못 입력하셨습니다.')
        break

print('결과:', result)

In [ ]:
# ## ✅ 문제 2. (중급 ⭐⭐⭐)

# **[랜덤 숫자 맞추기 게임]**

# ✅ 조건:

# - 1~100 사이 난수를 생성
# - 사용자가 맞출 때까지 반복
# - 입력값이 정답보다 크면 "너무 높아요", 작으면 "너무 낮아요" 출력
# - 정답을 맞추면 "축하합니다. 정답입니다." 출력 후 종료
# - 숫자가 아닌 값 입력 시 예외 처리

# ✅ 예시 실행:

# 1부터 100 사이의 숫자를 추측해보세요: 50
# 너무 높아요
# ...
# 축하합니다. 정답입니다.
import random

def exitChk(chk):
    if chk == 'q' or chk == 'Q': return True
    else: return False

val = random.randint(1,100)

while True:
    try:
        num = input('1부터 100 사이의 숫자를 추측해보세요:')
        if exitChk(num) == True:
            print('종료합니다.')
            break
        else: num = int(num)

        if val < num:
            print('너무 높아요')
        elif val > num:
            print('너무 낮아요')
        else:
            print('축하합니다. 정답입니다.')
            break

    except ValueError:
        print('숫자를 입력하세요.')




In [ ]:
# ## ✅ 문제 3. (중급 ⭐⭐⭐)

# **[복권 번호 맞추기 게임]**

# ✅ 조건:

# - 10부터 99까지의 난수(2자리 정수)를 생성
# - 사용자가 맞출 때까지 반복
# - 힌트: 입력값이 정답과 일치하지 않으면 "다시 시도하세요" 출력
# - 맞으면 "당첨! 복권 번호는 [번호]입니다" 출력

# ✅ 예시 실행:
# 복권 번호를 맞춰보세요(10~99): 25
# 다시 시도하세요.
# ...
# 당첨! 복권 번호는 47입니다.

import random

def exitChk(chk):
    if chk == 'q' or chk == 'Q': return True
    else: return False

result = random.randint(10,99)

while True:
    try:
        num = input('복권 번호를 맞춰보세요(10~99):')
        if exitChk(num) == True:
            print('종료합니다.')
            break
        else: num = int(num)

        if num < 10 or num >= 100:
            print('10~99 사이의 숫자를 입력하세요.')
            continue   

        if result == num:
            print(f'당첨! 복권 번호는 {result}입니다.')
            break
        else:
           print('다시 시도하세요.') 
    except ValueError:
        print('숫자를 입력하세요.')





In [ ]:
# ## ✅ 문제 4. (중급 ⭐⭐⭐)

# **[리스트의 점수 → 등급 변환 함수 작성하기]**

# ✅ 조건:

# - 리스트 형태의 점수(0~100)를 받아서
# - 90점 이상: 'A', 80점 이상: 'B', 70점 이상: 'C', 그 이하: 'F'
# - 변환된 리스트를 반환
# - 함수 이름: `grades()`

def grades(arr):
    total_arr = []
    for i in arr:
        score = ""
        if i >= 90:
            score = 'A'
        elif i < 90 and i >= 80:
            score = 'B'  
        elif i < 80 and i >= 70:
            score = 'C'
        else:
            score = 'F'  
        total_arr.append(score)
    return total_arr


strs = input('점수를 입력하세요.(ex 98 99 50 78 82):')

numbers = strs.split()
print(numbers)
try:
    scores = []
    for s in numbers:
        s = int(s)
        scores.append(s)

    print(grades(scores))


except ValueError:
    print('정수를 입력하세요.')




    



In [66]:
## 문제 5. (중급 ⭐⭐⭐)

# **[숫자 리스트에서 가장 많이 나온 값 찾기]**

# ✅ 조건:

# - 사용자로부터 숫자 여러 개 입력받아 리스트 생성
# - 리스트에서 가장 많이 등장한 값을 찾아 출력
# - (동점이면 아무거나 출력 가능)

# ✅ 예시 실행:

# 입력: [1, 3, 2, 3, 4, 3, 2, 2]
# 출력: 3
arr = input('숫자를 입력하세요.(ex 1 3 2 3 4 3 2 2):')

split_arr = arr.split()

print('입력 값 : ',split_arr)

try:
    ints = []
    #int 처리
    for s in split_arr:
        s = int(s)
        ints.append(s)

    #정렬
    ints.sort()

    #딕셔너리를 이용한 가장 많이 등장한 값 처리
    dic = {}
    for i in ints:
        if dic.get(i) == None:
            dic[i] = 1
        else:
            dic[i] = dic.get(i) + 1

    max_cnt = max(dic.values())

    #가장 많이 나온 값들 추출 
    result_arr = []

    for i in dic:
        if dic[i] == max_cnt:
            result_arr.append(i)
            #문제처럼 '동점이면 아무거나 출력 가능' 이게 있으면 아래처럼 해도 상관없음
            result = i

    # print(f'출력 가장많이 나온값 {result}, 나온 횟수 {max_cnt}' )
        
    print(f'출력 가장많이 나온값 {result_arr}, 나온 횟수 {max_cnt}' )

    


except ValueError:
    print('정수를 입력하세요.')



입력 값 :  []
정수를 입력하세요.


In [71]:
## 문제 6. (중급 ⭐⭐⭐)

# **[문자열에서 문자 개수 세기]**

# ✅ 조건:

# - 문자열을 입력받아
# - 각 문자가 몇 번 나왔는지 딕셔너리로 출력
# - 대소문자 구분 X

# ✅ 예시 실행:

# 입력: 'Hello World'
# 출력: {'h':1, 'e':1, 'l':3, 'o':2, 'w':1, 'r':1, 'd':1}

msg = input('문자를 입력하세요.')

try:

    #딕셔너리를 이용한 가장 많이 등장한 값 처리
    dic = {}
    msg = msg.lower()
    
    for i in msg:
        if i == ' ':
            continue

        if dic.get(i) == None:
            dic[i] = 1
        else:
            dic[i] = dic.get(i) + 1

    dic.values()
    print(dic)

except Exception as e:
    print('에러 발생 : ', e)




{}


In [92]:
## ✅ 문제 7. (중급 ⭐⭐⭐)

# **[2차원 배열 생성 - 대각선 1로 초기화]**

# ✅ 조건:

# - NumPy로 5x5 배열 생성
# - 대각선 값만 1, 나머지는 0
# - 출력

# ✅ 예시 출력:

import numpy as np

arr = np.zeros((5,5))

#방법1
np.fill_diagonal(arr, '1')


#방법2
# for i in range(arr.shape[0]):
#     arr[i, i] = 1


print(arr)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [97]:
## ✅ 문제 8. (중급 ⭐⭐⭐)

# **[NumPy 배열의 표준편차 구하기]**

# ✅ 조건:

# - 0~15까지의 정수로 이루어진 4x4 배열 생성
# - 배열의 표준편차 출력

# ✅ 예시 출력:

# 표준편차: 4.61

import numpy as np


arr = np.arange(0,16).reshape(4,4)

result = np.std(arr)

print(round(result, 2))


4.61


In [119]:
## ✅ 문제 9. (중급 ⭐⭐⭐)

# **[소수인지 판별 함수]**

# ✅ 조건:

# - 숫자를 입력받아
# - 소수이면 True, 아니면 False를 반환하는 함수 작성
# - 1은 소수가 아님


import numpy as np

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5)+1):
        # 2부터 √n까지 반복.
        # 이유: 약수가 있으면 한 쌍은 반드시 √n 이하에 존재
        # 예) 12의 약수 쌍: (2,6), (3,4)
        if n % i == 0:
            return False
    return True

try:

    #하나의 숫자를 받았을떄
    # num = int(input('숫자를 입력하세요.'))

    # result = is_prime(num)

    # if result == True:
    #     print('소수입니다. ',result)
    # else:
    #     print('해당 숫자는 소수가 아닙니다.')


    #1차원배열 처리
    # nums = np.arange(0,16)
    # results = [is_prime(x) for x in nums]

    #2차원배열 처리
    #vectorize - 파이썬의 일반 함수를 넘파이 배열의 각 원소에 적용하도록 만들어 주는 유틸리티 함수
    nums = np.arange(0,16).reshape(4,4)
    is_prime_vec = np.vectorize(is_prime)
    results = is_prime_vec(nums)

    print(results)

except ValueError:
    print('숫자를 입력하세요.')




[[False False  True  True]
 [False  True False  True]
 [False False False  True]
 [False  True False False]]


In [130]:
# **[NumPy 배열의 짝수 여부 판별 및 추출 함수 작성]**

# ✅ 조건:

# - 1차원 NumPy 배열을 입력받아
    
#     1️⃣ 각 요소가 짝수인지 여부를 판별한 **불리언 배열**을 반환
    
#     2️⃣ 배열에서 짝수인 값들만 **추출한 배열**도 반환
    
# - 두 결과를 **함수에서 튜플로 반환**

# ✅ 함수 예시 시그니처:
# def check_and_extract_even(arr):
#     ...
#     return even_mask, even_values
# ✅ 예시 실행:
# 입력 배열: [1, 2, 3, 4, 5, 6]
# 출력:
# 짝수 여부: [False, True, False, True, False, True]
# 짝수 값 추출: [2 4 6]

import numpy as np

# mask 사용
def check_and_extract_even(arr):
    arr = np.array(arr)

    even_mask = arr % 2 == 0
    even_values = arr[even_mask]

    return even_mask, even_values

try:

    arr = input('숫자를 입력해주세요. 입력 예시 [1, 2, 3, 4, 5, 6]')

    split_arr = arr.split(',')

    ints = []
    #int 처리
    for s in split_arr:
        s = int(s)
        ints.append(s)
  
    result_mask_arr, result_val_arr = check_and_extract_even(ints)

    print(result_mask_arr)
    print(result_val_arr)
    

except ValueError:
    print('숫자를 입력하세요.')





숫자를 입력하세요.


In [ ]:
# ## ✅ 문제 12. (중급 ⭐⭐⭐)

# **[상속 클래스에서 별도의 함수 추가 구현]**

# 아래 조건을 만족하는 부모 클래스(Person)와 자식 클래스(Student)를 파이썬으로 구현하세요:

# ✅ 부모 클래스: `Person`

# - 속성: name(이름), age(나이)
# - 생성자에서 name, age 초기화
# - introduce() 메서드
#     - 출력: "저는 [name], [age]살입니다."

# ✅ 자식 클래스: `Student`

# - `Person` 클래스를 상속
# - 추가 속성: major(전공)
# - 생성자에서 name, age, major 초기화 (부모 생성자 호출)
# - study() 메서드
#     - 출력: "[name]이(가) [major]를 공부합니다."

# ✅ 예시 실행:

# ```
# student = Student("Bob", 20, "Computer Science")
# student.introduce()
# student.study()

# 저는 Bob, 20살입니다.
# Bob이(가) Computer Science를 공부합니다.
# ```

class Person:

    def __init__(self, name, age):
        self.name = name
        self.age = age
    
    def introduce(self):
        print(f'저는 {name}, {age}살입니다.')


class Student(Person):
    def __init__(self):
        super.__init__()