In [ ]:
# ## ✅ 문제 1. (중급 ⭐⭐⭐)

# **[계산기 프로그램 만들기]**

# ✅ 조건:

# - 사용자로부터 숫자 2개와 연산자(+, -, *, /)를 입력받는다.
# - 해당 연산을 수행하고 결과를 출력한다.
# - 0으로 나누는 경우 예외 처리한다.

# ✅ 예시 실행:

# ```
# javascript
# 복사편집
# 첫 번째 숫자를 입력하세요: 10
# 두 번째 숫자를 입력하세요: 2
# 연산자를 입력하세요 (+, -, *, /): /
# 결과: 5.0

# ```


try:
    num1 = int(input('첫 번째 숫자를 입력하세요:'))

    num2 = int(input('두 번째 숫자를 입력하세요:'))

    t = input('연산자를 입력하세요 (+, -, *, /):')
    reuslt = 0
    if t == '+':
        reuslt =num1 + num2
    elif t == '-':
        reuslt =num1 - num2
    elif t == '*':
        reuslt =num1 * num2
    elif t == '/':
        if num1 == 0 or num2 == 0:
            raise ValueError('0으로 나눌 수 없습니다.')
        reuslt =num1 / num2
    else:
        raise ValueError('연산자 오류 :'+t)

    print('결과 : ', reuslt)

except ValueError as e:
    print('잘못된 입력입니다.', e)


In [ ]:
# ## ✅ 문제 2. (중급 ⭐⭐⭐)

# **[랜덤 숫자 맞추기 게임]**

# ✅ 조건:

# - 1~100 사이 난수를 생성
# - 사용자가 맞출 때까지 반복
# - 입력값이 정답보다 크면 "너무 높아요", 작으면 "너무 낮아요" 출력
# - 정답을 맞추면 "축하합니다. 정답입니다." 출력 후 종료
# - 숫자가 아닌 값 입력 시 예외 처리

# ✅ 예시 실행:

# 1부터 100 사이의 숫자를 추측해보세요: 50
# 너무 높아요
# ...
# 축하합니다. 정답입니다.


import random 

random_result = random.randint(1,100)

while True:
    try:
        num = int(input('1부터 100 사이의 숫자를 추측해보세요:'))

        if num > random_result:
            print('너무 높아요')
        elif num < random_result:
            print('너무 낮아요')
        else:
            print('축하합니다. 정답입니다.')
            break

    except ValueError as e:
        print('잘못된 입력입니다. ', e)



In [ ]:
# ## ✅ 문제 3. (중급 ⭐⭐⭐)

# **[복권 번호 맞추기 게임]**

# ✅ 조건:

# - 10부터 99까지의 난수(2자리 정수)를 생성
# - 사용자가 맞출 때까지 반복
# - 힌트: 입력값이 정답과 일치하지 않으면 "다시 시도하세요" 출력
# - 맞으면 "당첨! 복권 번호는 [번호]입니다" 출력

# ✅ 예시 실행:
# 복권 번호를 맞춰보세요(10~99): 25
# 다시 시도하세요.
# ...
# 당첨! 복권 번호는 47입니다.

import random

def exitChk(msg):
    if msg == 'q' or msg == 'Q':
        return True
    else:
        return False

random_int = random.randint(10,99)

while True:
    try:
        num = input('복권 번호를 맞춰보세요(10~99):')
        if exitChk(num) == True:
            print('종료합니다.')
            break
        else:
            num = int(num)

        if num < 10 or num >= 100:
            print('10~99사이의 값을 넣으세요.')
            continue


        if num == random_int:
            print(f'당첨! 복권 번호는 {random_int}입니다.')
        else:
            print('다시 시도하세요.')

    except ValueError as e:
        print('잘못된 입력입니다. ', e)




In [ ]:
# ## ✅ 문제 4. (중급 ⭐⭐⭐)

# **[리스트의 점수 → 등급 변환 함수 작성하기]**

# ✅ 조건:
# - 리스트 형태의 점수(0~100)를 받아서
# - 90점 이상: 'A', 80점 이상: 'B', 70점 이상: 'C', 그 이하: 'F'
# - 변환된 리스트를 반환
# - 함수 이름: `grades()`

def grades(arr):
    return_arr = []
    
    for i in arr:
        t = ""
        if i >= 90:
            t = "A"
        elif i >= 80 and i < 90:
            t = "B"
        elif i >= 70 and i < 80:
            t = "C"
        else:
            t = "F"
        return_arr.append(t)
    return return_arr
    



try:
    arr_input = input('점수를 입력하세요. (예시 98 50 72 88):')

    arr = arr_input.split()

    ints = []
    for i in arr:
        ints.append(int(i))

    reuslt_arr = grades(ints)
    print(reuslt_arr)

except ValueError as e:
    print('잘못된 입력입니다. ', e)



In [ ]:
## 문제 5. (중급 ⭐⭐⭐)

# **[숫자 리스트에서 가장 많이 나온 값 찾기]**

# ✅ 조건:

# - 사용자로부터 숫자 여러 개 입력받아 리스트 생성
# - 리스트에서 가장 많이 등장한 값을 찾아 출력
# - (동점이면 아무거나 출력 가능)

# ✅ 예시 실행:

# 입력: [1, 3, 2, 3, 4, 3, 2, 2]
# 출력: 3


try:
    input_arr = input('숫자 리스트를 입력하세요.(ex 1, 3, 2, 3, 4, 3, 2, 2)')

    split_arr = input_arr.split(',')

    split_arr.sort()

    dic = {}

    for i in split_arr:
        if dic.get(i) == None:
            dic[i] = 1
        else:
            dic[i] = dic.get(i) + 1

    max_key = 0
    max_val = max(dic.values())
    for key, val in dic.items():
        if val == max_val:
            max_key = key
            break

    print(f"가장 많이 나온 숫자 {max_key}, 나온 횟수 {max_val}")

except ValueError as e:
    print('잘못된 입력입니다. ',e)



In [ ]:
## 문제 6. (중급 ⭐⭐⭐)

# **[문자열에서 문자 개수 세기]**

# ✅ 조건:

# - 문자열을 입력받아
# - 각 문자가 몇 번 나왔는지 딕셔너리로 출력
# - 대소문자 구분 X

# ✅ 예시 실행:

# 입력: 'Hello World'
# 출력: {'h':1, 'e':1, 'l':3, 'o':2, 'w':1, 'r':1, 'd':1}


msg = input('문자열 입력 : ')

msg = msg.lower()

dic = {}
for t in msg:
    if t == ' ':
        continue

    if dic.get(t) == None:
        dic[t] = 1
    else:
        dic[t] = dic.get(t) + 1

print(dic)

In [ ]:
## ✅ 문제 7. (중급 ⭐⭐⭐)

# NumPy를 사용해 4x4 단위 행렬(대각선만 1, 나머지 0)을 생성하고 출력하세요.
# 그리고 0부터 15까지의 정수로 이루어진 4x4 배열을 만들어서,

# 행별 합계
# 열별 합계
# 전체 평균
# 전체 표준편차
# 를 계산해 출력하세요

# ✅ 예시 출력:


# 단위 행렬:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]
#
# 배열:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]
#
# 행별 합계: [ 6 22 38 54]
# 열별 합계: [24 28 32 36]
# 전체 평균: 7.5
# 전체 표준편차: 4.61

import numpy as np


zero_arr = np.zeros((4,4))

np.fill_diagonal(zero_arr, '1')

print(zero_arr)

arr = np.arange(0,16).reshape(4,4)
print(arr)

sum_low_arr = np.sum(arr, axis=1)
sum_col_arr = np.sum(arr, axis=0)

print('행별 합계: ',sum_low_arr)
print('열별 합계: ',sum_col_arr)
print('전체 평균: ',np.mean(arr))
print('전체 표준편차: ',round(np.std(arr),2))


In [ ]:
## ✅ 문제 9. (중급 ⭐⭐⭐)

# **[소수인지 판별 함수]**

# ✅ 조건:

# - 숫자를 입력받아
# - 소수이면 True, 아니면 False를 반환하는 함수 작성
# - 1은 소수가 아님




In [ ]:
# **[NumPy 배열의 짝수 여부 판별 및 추출 함수 작성]**

# ✅ 조건:

# - 1차원 NumPy 배열을 입력받아
    
#     1️⃣ 각 요소가 짝수인지 여부를 판별한 **불리언 배열**을 반환
    
#     2️⃣ 배열에서 짝수인 값들만 **추출한 배열**도 반환
    
# - 두 결과를 **함수에서 튜플로 반환**

# ✅ 함수 예시 시그니처:
# def check_and_extract_even(arr):
#     ...
#     return even_mask, even_values
# ✅ 예시 실행:
# 입력 배열: [1, 2, 3, 4, 5, 6]
# 출력:
# 짝수 여부: [False, True, False, True, False, True]
# 짝수 값 추출: [2 4 6]



In [ ]:
# ## ✅ 문제 12. (중급 ⭐⭐⭐)

# **[상속 클래스에서 별도의 함수 추가 구현]**

# 아래 조건을 만족하는 부모 클래스(Person)와 자식 클래스(Student)를 파이썬으로 구현하세요:

# ✅ 부모 클래스: `Person`

# - 속성: name(이름), age(나이)
# - 생성자에서 name, age 초기화
# - introduce() 메서드
#     - 출력: "저는 [name], [age]살입니다."

# ✅ 자식 클래스: `Student`

# - `Person` 클래스를 상속
# - 추가 속성: major(전공)
# - 생성자에서 name, age, major 초기화 (부모 생성자 호출)
# - study() 메서드
#     - 출력: "[name]이(가) [major]를 공부합니다."

# ✅ 예시 실행:

# ```
# student = Student("Bob", 20, "Computer Science")
# student.introduce()
# student.study()

# 저는 Bob, 20살입니다.
# Bob이(가) Computer Science를 공부합니다.
# ```

class Person():
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def introduce(self):
        print(f"저는 {self.name}, {self.age}살입니다.")

class Student(Person):
    def __init__(self, name, age, major):
        super().__init__(name, age)
        self.major = major

    def study(self):
        print(f"{self.name}이(가) {self.major}를 공부합니다.")
        

student = Student("Bob", 20, "Computer Science")
student.introduce()
student.study()


In [ ]:
# - ✅ 문제 1 (쉬움 ⭐️)
# 문제:
# NumPy를 사용하여 1부터 12까지의 정수를 가진 배열을 생성하고, (3,4) 형태로 변환하세요.
# 변환된 배열을 출력하세요.

# ```

# # ✅ 예시 출력:

# # [[ 1  2  3  4]
# #  [ 5  6  7  8]
# #  [ 9 10 11 12]]
# ```
import numpy as np

arr = np.arange(1,13).reshape(3,4)

print(arr)

In [ ]:

# - ✅ 문제 2 (중간 ⭐⭐⭐)
# 문제:
# 다음 배열에서 5보다 큰 값은 1, 나머지는 0으로 설정하는 마스크 배열을 생성하고 출력하세요.

# ```

# # ✅ 조건:

# # 배열 내용:
# # [[3, 5, 7],
# #  [2, 8, 6],
# #  [4, 1, 9]]
# # ✅ 예시 출력:

# # [[0 0 1]
# #  [0 1 1]
# #  [0 0 1]]
# ```

arr = np.array([[3, 5, 7],
 [2, 8, 6],
 [4, 1, 9]])

mask_arr = np.zeros(arr.shape)

mask_arr[arr > 5] = 1

print(mask_arr)



#필수문제
# 이미지
# 트랙바를 세팅하여 마스크에 특정 색 검출 기능 구현
# 해당 색에 사각형 표시  
# HSV(RGBx) 사용 

하급
  ① 이미지 로딩 + 출력
  ② HSV 변환 + 출력
  ③ 고정 색 범위 → 마스크 생성

중급
  ④ 마스크로 색상만 추출
  ⑤ 마스크 → 윤곽선 → 사각형 표시
  ⑥ 트랙바로 HSV 범위 조정 + 색상 검출 + 사각형 강조


✅ ⭐️ 하급 문제 ①

# ⭐️ 문제 1
# [이미지 읽어서 출력하기]

✅ 조건:
- 이미지 파일을 읽어서 화면에 출력

✅ 목표 함수:
- cv2.imread()
- cv2.imshow()
- cv2.waitKey()


✅ ⭐️ 하급 문제 ②

# ⭐️ 문제 2
# [이미지를 HSV 색공간으로 변환하여 출력하기]

✅ 조건:
- BGR 이미지를 HSV 색공간으로 변환
- 원본 BGR 이미지와 HSV 이미지를 각각 출력

✅ 목표 함수:
- cv2.cvtColor()
- cv2.imshow()


✅ ⭐️ 하급 문제 ③

# ⭐️ 문제 3
# [고정 색상 범위로 마스크 생성하기]

✅ 조건:
- HSV 이미지에서 특정 색상 범위(H_min ~ H_max, S_min ~ S_max, V_min ~ V_max)를 지정
- cv2.inRange()를 사용해 마스크 생성
- 마스크 출력

✅ 목표 함수:
- cv2.inRange()
- cv2.imshow()


✅ ⭐️ 중급 문제 ④

# ⭐️ 문제 4
# [마스크로 색상 영역만 추출하기]

✅ 조건:
- inRange로 만든 마스크를 사용해
- 원본 이미지에서 특정 색상 영역만 컬러로 유지
- 나머지는 제거(검정색 처리)
- 결과 출력

✅ 목표 함수:
- cv2.bitwise_and()
- cv2.imshow()

✅ ⭐️ 중급 문제 ⑤

# ⭐️ 문제 5
# [마스크에서 윤곽선 검출 + 사각형 표시]

✅ 조건:
- cv2.findContours()로 마스크에서 윤곽선 탐색
- 각 검출된 윤곽선의 외접 사각형(bounding box) 계산
- 원본 이미지 위에 사각형을 그려 강조
- 결과 출력

✅ 목표 함수:
- cv2.findContours()
- cv2.boundingRect()
- cv2.rectangle()
- cv2.imshow()


✅ ⭐️ 통합 문제

# ⭐️ 문제 6
# [트랙바로 색상 범위 조정 + 색상 검출 + 사각형 표시 (통합 프로그램)]

✅ 조건:
- 이미지에서 HSV 색공간 변환
- 트랙바(슬라이더) UI로 H/S/V의 min/max 값 실시간 조정
- inRange로 마스크 생성
- 마스크로 색상 영역만 컬러 유지
- 윤곽선 검출 후 사각형으로 강조
- 결과를 실시간으로 출력

✅ 목표 함수:
- cv2.createTrackbar()
- cv2.getTrackbarPos()
- cv2.inRange()
- cv2.bitwise_and()
- cv2.findContours()
- cv2.boundingRect()
- cv2.rectangle()
- cv2.imshow()

In [ ]:
# ✅ ⭐️ 하급 문제 ①

# # ⭐️ 문제 1
# # [이미지 읽어서 출력하기]

# ✅ 조건:
# - 이미지 파일을 읽어서 화면에 출력

# ✅ 목표 함수:
# - cv2.imread()
# - cv2.imshow()
# - cv2.waitKey()
import cv2 


img_path = 'example1.jpg'

img = cv2.imread(img_path)

cv2.imshow('test',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# ✅ ⭐️ 하급 문제 ②

# # ⭐️ 문제 2
# # [이미지를 HSV 색공간으로 변환하여 출력하기]

# ✅ 조건:
# - BGR 이미지를 HSV 색공간으로 변환
# - 원본 BGR 이미지와 HSV 이미지를 각각 출력

# ✅ 목표 함수:
# - cv2.cvtColor()
# - cv2.imshow()

import cv2 


img = cv2.imread('example1.jpg')

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

cv2.imshow('hsv',hsv)
cv2.imshow('img',img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
# ✅ ⭐️ 하급 문제 ③

# # ⭐️ 문제 3
# # [고정 색상 범위로 마스크 생성하기]

# ✅ 조건:
# - HSV 이미지에서 특정 색상 범위(H_min ~ H_max, S_min ~ S_max, V_min ~ V_max)를 지정
# - cv2.inRange()를 사용해 마스크 생성
# - 마스크 출력

# ✅ 목표 함수:
# - cv2.inRange()
# - cv2.imshow()

import cv2 
import numpy as np

img = cv2.imread('example1.jpg')

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

low = np.array([10,100,100])
upper = np.array([50,255,255])

mask = cv2.inRange(hsv, low,upper)

cv2.imshow('hsv',hsv)
cv2.imshow('img',img)
cv2.imshow('mask', mask)

cv2.waitKey(0)
cv2.destroyAllWindows()


In [ ]:

# ✅ ⭐️ 중급 문제 ④

# # ⭐️ 문제 4
# # [마스크로 색상 영역만 추출하기]

# ✅ 조건:
# - inRange로 만든 마스크를 사용해
# - 원본 이미지에서 특정 색상 영역만 컬러로 유지
# - 나머지는 제거(검정색 처리)
# - 결과 출력

# ✅ 목표 함수:
# - cv2.bitwise_and()
# - cv2.imshow()

import cv2 
import numpy as np

img = cv2.imread('color_test.jpg')

img = cv2.resize(img, (680, 480))

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# 빨간색을 제외한 이미지 범위 설정
# low = np.array([5,30,30])
# upper = np.array([180,255,255])
# mask = cv2.inRange(hsv, low, upper)

# 빨간색 이미지 범위 설정
# 빨간색 범위 두 구간 정의
low1 = np.array([0, 100, 100])
upper1 = np.array([10, 255, 255])

low2 = np.array([170, 100, 100])
upper2 = np.array([180, 255, 255])

# 각각의 마스크
mask1 = cv2.inRange(hsv, low1, upper1)
mask2 = cv2.inRange(hsv, low2, upper2)

# 두 마스크 합치기
mask = cv2.bitwise_or(mask1, mask2)


result = cv2.bitwise_and(img, img, mask=mask)

cv2.imshow('result', result)

cv2.waitKey(0)
cv2.destroyAllWindows()



In [ ]:
# ✅ ⭐️ 중급 문제 ⑤

# # ⭐️ 문제 5
# # [마스크에서 윤곽선 검출 + 사각형 표시]

# ✅ 조건:
# - cv2.findContours()로 마스크에서 윤곽선 탐색
# - 각 검출된 윤곽선의 외접 사각형(bounding box) 계산
# - 원본 이미지 위에 사각형을 그려 강조
# - 결과 출력

# ✅ 목표 함수:
# - cv2.findContours()
# - cv2.boundingRect()
# - cv2.rectangle()
# - cv2.imshow()

import cv2
import numpy as np

img = cv2.imread('color_test.jpg')

img = cv2.resize(img, (680,480))

hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

# 빨간색을 제외한 이미지 범위 설정
# low = np.array([5,30,30])
# upper = np.array([180,255,255])
# mask = cv2.inRange(hsv, low, upper)

# 빨간색 이미지 범위 설정
# 빨간색 범위 두 구간 정의
low1 = np.array([0, 100, 100])
upper1 = np.array([10, 255, 255])

low2 = np.array([170, 100, 100])
upper2 = np.array([180, 255, 255])

# 각각의 마스크
mask1 = cv2.inRange(hsv, low1, upper1)
mask2 = cv2.inRange(hsv, low2, upper2)

# 두 마스크 합치기
mask = cv2.bitwise_or(mask1, mask2)

# 윤곽선 검출
# cv2.RETR_EXTERNAL 윤곽선 계층 구조를 선택하는 모드 가장 바깥쪽(External) 윤곽선만 찾는다
# cv2.CHAIN_APPROX_SIMPLE 윤곽선 점들을 단순화하는 방식 직선 구간의 중간 점들을 버리고 꼭짓점만 남김
contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# 각 윤곽선을 감싸는 가장 작은 직사각형을 계산해서, 이미지 위에 녹색 테두리로 그려주는 코드
# contours는 → cv2.findContours()가 찾아준 윤곽선들의 리스트
for cnt in contours:
    # 입력된 윤곽선(점들의 집합)을 완전히 포함하는 가장 작은 수평 직사각형을 계산
    #x, y: 사각형의 왼쪽 위 꼭짓점 좌표
    # w, h: 사각형의 너비(width), 높이(height)
    x, y, w, h = cv2.boundingRect(cnt)

    # 실제 이미지 위에 사각형을 그리는 함수
    cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)


cv2.imshow('result', img)

cv2.waitKey(0)
cv2.destroyAllWindows()



In [1]:
# ✅ ⭐️ 통합 문제

# # ⭐️ 문제 6
# # [트랙바로 색상 범위 조정 + 색상 검출 + 사각형 표시 (통합 프로그램)]

# ✅ 조건:
# - 이미지에서 HSV 색공간 변환
# - 트랙바(슬라이더) UI로 H/S/V의 min/max 값 실시간 조정
# - inRange로 마스크 생성
# - 마스크로 색상 영역만 컬러 유지
# - 윤곽선 검출 후 사각형으로 강조
# - 결과를 실시간으로 출력

# ✅ 목표 함수:
# - cv2.createTrackbar()
# - cv2.getTrackbarPos()
# - cv2.inRange()
# - cv2.bitwise_and()
# - cv2.findContours()
# - cv2.boundingRect()
# - cv2.rectangle()
# - cv2.imshow()

import cv2
import numpy as np

def do_pass(x):
    pass

img = cv2.imread('color_test.jpg')
img = cv2.resize(img, (800, 500))



# ② 트랙바용 윈도우 생성
cv2.namedWindow('Trackbars')

#트랙바 생성
cv2.createTrackbar('h_min','Trackbars', 0,179, do_pass)
cv2.createTrackbar('s_min','Trackbars', 0,254, do_pass)
cv2.createTrackbar('v_min','Trackbars', 0,254, do_pass)

cv2.createTrackbar('h_max','Trackbars', 179,179, do_pass)
cv2.createTrackbar('s_max','Trackbars', 255,255, do_pass)
cv2.createTrackbar('v_max','Trackbars', 255,255, do_pass)


while True:
    try:
        hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

        h_min = cv2.getTrackbarPos('h_min','Trackbars')
        s_min = cv2.getTrackbarPos('s_min','Trackbars')
        v_min = cv2.getTrackbarPos('v_min','Trackbars')
        h_max = cv2.getTrackbarPos('h_max','Trackbars')
        s_max = cv2.getTrackbarPos('s_max','Trackbars')
        v_max = cv2.getTrackbarPos('v_max','Trackbars')

        low = np.array([h_min, s_min, v_min])
        upper = np.array([h_max, s_max, v_max])

        mask = cv2.inRange(hsv, low, upper)

        # ⑦ 마스크 적용해 색상 추출
        result = cv2.bitwise_and(img, img, mask=mask)

        # ⑨ 원본 복사
        output = img.copy()

        # ⑧ 윤곽선 검출
        contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


        # ⑩ 윤곽선마다 사각형 그리기
        for cnt in contours:
            area = cv2.contourArea(cnt)
            if area > 100:  # 너무 작은 잡음은 무시
                x, y, w, h = cv2.boundingRect(cnt)
                cv2.rectangle(output, (x, y), (x + w, y + h), (0, 255, 0), 2)

        # ⑪ 결과 출력
        # cv2.imshow('Original', img)
        cv2.imshow('result',result)
        cv2.imshow('Mask', mask)
        cv2.imshow('Trackbars', output)


        # 종료 조건
        if cv2.waitKey(1) & 0xFF == 27:  # ESC 키
            break
    except Exception as e:
        break

cv2.destroyAllWindows()