In [ ]:
# ✅ 문제 1 (쉬움 ⭐️)
# 문제:
# 사용자로부터 이름과 나이를 입력받아 딕셔너리 형태로 저장하고 출력하는 프로그램을 작성하세요.

# ✅ 예시 실행:

# bash
# 복사
# 편집
# 이름을 입력하세요: Alice
# 나이를 입력하세요: 25
# {'name': 'Alice', 'age': 25}


name = input('이름을 입력하세요.:')
age = input('나이를 입력하세요.:')

dic = {}

dic['name'] = name
dic['age'] = int(age)

print(dic)



In [ ]:
# ✅ 문제 2 (중간 ⭐⭐⭐)
# 문제:
# 아래 조건을 모두 만족하는 프로그램을 작성하세요.

# 사용자로부터 과목 이름과 점수를 반복해서 입력받아 딕셔너리에 저장

# 'exit'를 입력하면 입력 종료

# 모든 입력이 끝난 후 과목별 점수 출력

# 평균 점수를 계산하여 출력

# ✅ 예시 실행:

# 과목을 입력하세요 (exit 입력 시 종료): 파이썬
# 점수를 입력하세요: 90
# 과목을 입력하세요 (exit 입력 시 종료): 아두이노
# 점수를 입력하세요: 85
# 과목을 입력하세요 (exit 입력 시 종료): exit

# 입력한 점수:
# 파이썬: 90
# 아두이노: 85
# 평균 점수: 87.5
dic = {}
while True:
    t = input("과목을 입력하세요 (exit 입력 시 종료):")
   

    if t == 'exit':
        break
    else:
        num = input("점수를 입력하세요:")
        dic[t] = int(num)
print(dic)
avg = 0
print('입력한 점수:')
for key in dic:
    print(f'{key} : {dic[key]}')
    avg += int(dic[key])
avg = avg/len(dic)
print('평균 점수:',avg)




In [ ]:
# ✅ 문제 3 (중간 ⭐⭐⭐)
# 문제:
# 아래 조건을 만족하는 리스트 프로그램을 작성하세요.

# 사용자로부터 원하는 과일 이름을 계속 입력받아 리스트에 추가

# 'done'을 입력하면 입력 종료

# 알파벳순으로 정렬하여 출력

# 중복된 과일 이름은 제거

# ✅ 예시 실행:

# 과일을 입력하세요 (done 입력 시 종료): apple
# 과일을 입력하세요 (done 입력 시 종료): banana
# 과일을 입력하세요 (done 입력 시 종료): apple
# 과일을 입력하세요 (done 입력 시 종료): cherry
# 과일을 입력하세요 (done 입력 시 종료): done

# 결과: ['apple', 'banana', 'cherry']
arr = []
while True:

    t = input('과일을 입력하세요 (done 입력 시 종료)')

    if t == 'done':
        test = set(arr)
        arr = list(test)
        arr.sort()
        break
    else:
        arr.append(t)

print(arr)


In [ ]:
# ✅ 문제 4 (어려움 ⭐⭐⭐⭐)
# 문제:
# 다음 기능을 모두 수행하는 “장바구니 프로그램”을 작성하세요.

# 사전에 정의된 상품 목록이 있음 (딕셔너리 사용, 예: {"apple":1000, "banana":500, "cherry":800})

# 사용자로부터 상품 이름과 수량을 반복해서 입력받아 장바구니에 추가

# 'q' 입력 시 입력 종료

# 장바구니에 담긴 상품과 수량, 총 가격 출력

# ✅ 예시 실행:

# 상품을 입력하세요 (종료는 q): apple
# 수량을 입력하세요: 2
# 상품을 입력하세요 (종료는 q): cherry
# 수량을 입력하세요: 3
# 상품을 입력하세요 (종료는 q): q

# 장바구니:
# apple: 2개
# cherry: 3개
# 총 가격: 4400원

dic = {"apple":1000, "banana":500, "cherry":800, "orange":1500}

result = {}

print("상품 목록 :", dic)
while True:

    txt = input('상품을 입력하세요 (종료는 q):')

    if txt == 'q':
        break
    elif dic.get(txt) == None:
        print('없는 상품입니다.')
    else:
        num = input('수량을 입력하세요:')

    if result.get(txt) == None:
        result[txt] = int(num)
    else:
        result[txt] = result.get(txt) + int(num)
total = 0
print('장바구니:')
for key in result:
    print(f'{key}: {result[key]}개 - {(dic[key] * result[key])}원')
    total += (dic[key] * result[key])
print(f'총 가격: {total}원')




In [ ]:
# ✅ 문제 5 (어려움 ⭐⭐⭐⭐)
# 문제:
# 아래 조건을 만족하는 파일 처리 프로그램을 작성하세요.

# 'my_favorites.txt'라는 텍스트 파일을 연다. 없으면 새로 생성

# 사용자로부터 좋아하는 단어를 계속 입력받아 파일에 추가

# 'exit' 입력 시 종료

# 마지막에 파일 내용을 한 줄씩 읽어와서 출력

# ✅ 예시 실행:

# 좋아하는 단어를 입력하세요 (exit 입력 시 종료): Robot
# 좋아하는 단어를 입력하세요 (exit 입력 시 종료): Python
# 좋아하는 단어를 입력하세요 (exit 입력 시 종료): exit

# 현재 파일 내용:
# Raindrops
# roses
# whiskers
# kittens
# Robot
# Python

from pathlib import Path

path = Path('my_favorites.txt')


while True:
    txt = input('좋아하는 단어를 입력하세요 (exit 입력 시 종료):')

    if txt == 'exit':
        break
    else:
        with path.open(mode='a') as file:
            file.write(txt + '\n')


print('현재 파일 내용:')
contents = path.read_text()
print(contents)


In [ ]:
# ✅ 문제 1 (쉬움 ⭐️)
# 문제:
# 사용자의 이름을 입력받아 인사하는 함수를 작성하고 호출하세요.

# ✅ 조건:

# 함수 이름은 greet로 한다.

# 입력받은 이름으로 "안녕하세요. [이름]님"을 출력한다.

# ✅ 예시 실행:

# 복사
# 편집
# 이름을 입력하세요: Alice
# 안녕하세요. Alice님


def greet(name):
    print(f'안녕하세요. {name}님')

greet(input('이름을 입력하세요:'))


In [ ]:
# ✅ 문제 2 (중간 ⭐⭐⭐)
# 문제:
# 두 수를 입력받아 합과 곱을 반환하는 함수를 작성하세요.
# 반환값은 튜플로 받고, 결과를 출력하세요.

# ✅ 조건:

# 함수 이름은 add_and_mul로 한다.

# 리턴값은 (합, 곱) 형태의 튜플

# 메인 코드에서 결과를 언패킹해서 각각 출력

# ✅ 예시 실행:

# 첫 번째 숫자: 3
# 두 번째 숫자: 4
# 합: 7
# 곱: 12

def add_and_mul(num1, num2):
    sum = num1 + num2
    multiplication = num1 * num2

    return (sum, multiplication)

num1 = int(input('첫 번째 숫자:'))
num2 = int(input('두 번째 숫자:'))

arr = add_and_mul(num1, num2)

print('합:',arr[0])
print('곱:',arr[1])



In [ ]:
# ✅ 문제 3 (중간 ⭐⭐⭐)
# 문제:
# 문자열을 입력받아 대문자로 변환하는 함수를 작성하고, 결과를 출력하세요.

# ✅ 조건:

# 함수 이름은 to_uppercase로 한다.

# 반복문으로 문자 하나씩 처리

# 반환된 결과를 출력

# ✅ 예시 실행:


# 문자열을 입력하세요: hello world
# 대문자 변환: HELLO WORLD



In [ ]:
# ✅ 문제 4 (어려움 ⭐⭐⭐⭐)
# 문제:
# Calculator 클래스를 작성하고 다음 기능을 구현하세요.

# ✅ 조건:

# 생성자에서 result 속성 초기화

# add, subtract, multiply, divide 메서드 구현 (result를 갱신)

# 사용자로부터 연산 선택(+,-,*,/), 숫자 두 개 입력 받아서 해당 연산 수행

# 결과 출력

# ✅ 예시 실행:

# 연산을 선택하세요 (+,-,*,/): +
# 첫 번째 숫자: 5
# 두 번째 숫자: 3
# 결과: 8

class Calculator:
    def __inif__(self):
        self.result = 0

    def add(self, num1, num2):
        return num1+num2

    def subtract(self, num1, num2):
        return num1-num2
    
    def multiply(self, num1, num2):
        return num1*num2
    def divide(self, num1, num2):
        return num1/num2
    

calc = Calculator()
total = 0
txt = input('연산을 선택하세요 (+,-,*,/):')

num1 = int(input('첫 번째 숫자:'))
num2 = int(input('두 번째 숫자:'))

if txt == '+':
    total = calc.add(num1, num2)
elif txt == '-':
    total = calc.subtract(num1, num2)    
elif txt == '*':
    total = calc.multiply(num1, num2)
elif txt == '/':
    total = calc.divide(num1, num2)
else:
    print('잘못 입력하셨습니다.')

print('결과', total)

In [ ]:
# ✅ 문제 5 (어려움 ⭐⭐⭐⭐)
# 문제:
# 랜덤 숫자 맞추기 게임을 함수와 예외처리를 사용해 작성하세요.

# ✅ 조건:

# 1부터 100 사이 난수 생성

# 사용자 입력이 int가 아니면 예외 처리 (ValueError)

# 입력값이 정답보다 크면 "너무 높아요", 작으면 "너무 낮아요" 출력

# 맞으면 "축하합니다. 정답입니다" 출력 후 종료

# ✅ 예시 실행:

# 1부터 100 사이의 숫자를 추측해보세요: 50
# 너무 높아요
# 프로그램 종료
# ...
# 1부터 100 사이의 숫자를 추측해보세요: 72
# 축하합니다. 정답입니다.
# 프로그램 종료
import random

randint = random.randint(1,100)

while True:
    try:
        s = input('1부터 100 사이의 숫자를 추측해보세요: ')
        if not s.strip():
            raise ValueError('빈 입력은 허용하지 않습니다.')
        num = int(s)
        
        if randint < num:
            print('너무 높아요')
        elif randint > num:
            print('너무 낮아요')
        else:
            print('축하합니다. 정답입니다.')
            break
    except ValueError:
        print('숫자를 입력하세요.')

print('프로그램 종료')


In [ ]:

# ✅ 문제 1 (쉬움 ⭐️)
# 문제:
# NumPy를 사용하여 1부터 12까지의 정수를 가진 배열을 생성하고, (3,4) 형태로 변환하세요.
# 변환된 배열을 출력하세요.

# ✅ 예시 출력:

# lua
# 복사
# 편집
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

import numpy as np

arr = np.arange(1,13).reshape(3,4)

print(arr)

In [ ]:
# ✅ 문제 2 (중간 ⭐⭐⭐)
# 문제:
# 다음 배열에서 5보다 큰 값은 1, 나머지는 0으로 설정하는 마스크 배열을 생성하고 출력하세요.

# ✅ 조건:


# 배열 내용:
# [[3, 5, 7],
#  [2, 8, 6],
#  [4, 1, 9]]
# ✅ 예시 출력:


# [[0 0 1]
#  [0 1 1]
#  [0 0 1]]

import numpy as np

arr = np.array([[3, 5, 7],[2, 8, 6],[4, 1, 9]])

mask = np.zeros(arr.shape)
mask[arr > 5] = 1

print(mask)


In [ ]:
# ✅ 문제 3 (중간 ⭐⭐⭐)
# 문제:
# 다음 배열에서

# 행별 합계

# 열별 합계

# 전체 평균
# 을 각각 계산하고 출력하세요.

# ✅ 조건 배열:

# [[10, 20, 30],
#  [40, 50, 60],
#  [70, 80, 90]]
# ✅ 예시 출력:

# 행별 합계: [ 60 150 240]
# 열별 합계: [120 150 180]
# 전체 평균: 50.0

import numpy as np

arr = np.array([[10, 20, 30],[40, 50, 60],[70, 80, 90]])

sum_col_arr = np.sum(arr, axis=0)
sum_row_arr = np.sum(arr, axis=1)

print('행별 합계:', sum_row_arr)
print('열별 합계:', sum_col_arr)
print('전체 평균:', np.average(arr))

In [ ]:
# ✅ 문제 4 (어려움 ⭐⭐⭐⭐)
# 문제:
# Pandas를 사용하여 아래 데이터를 가진 DataFrame을 생성하고,

# 나이가 20 이상인 사람만 선택

# 선택된 사람의 평균 점수 계산 후 출력

# ✅ 데이터:

# Name: ['영희', '철수', '민수', '지민', '서연']
# Age: [21, 19, 22, 20, 18]
# Score: [88, 75, 92, 85, 70]
# ✅ 예시 출력:

# 나이 20 이상:
#     Name  Age  Score
# 0    영희   21     88
# 2    민수   22     92
# 3    지민   20     85

# 평균 점수: 88.33
import numpy as np
import pandas as pd

data = {
'Name' : ['영희', '철수', '민수', '지민', '서연'],
"Age" : [21, 19, 22, 20, 18],
'Score' : [88, 75, 92, 85, 70]}

df = pd.DataFrame(data)

df2 = df[df.Age >= 20]

avg = sum(df2['Score']) / len(df2)


print(df2)
print('평균 점수:',round(avg, 2))



In [ ]:
# ✅ 문제 5 (어려움 ⭐⭐⭐⭐)
# 문제:
# NumPy를 사용해 4x4 단위 행렬(대각선만 1, 나머지 0)을 생성하고 출력하세요.
# 그리고 0부터 15까지의 정수로 이루어진 4x4 배열을 만들어서,

# 행별 합계

# 열별 합계

# 전체 표준편차
# 를 계산해 출력하세요.

# ✅ 예시 출력:

# 단위 행렬:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

# 배열:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]
#  [12 13 14 15]]

# 행별 합계: [ 6 22 38 54]
# 열별 합계: [24 28 32 36]
# 전체 표준편차: 4.61

import numpy as np

arr1 = np.zeros((4,4))

np.fill_diagonal(arr1, 1)

print(arr1)

arr2 = np.arange(16).reshape(4,4)

print(arr2)

print('행별 합계: ', arr2.sum(axis=1))
print('열별 합계: ', arr2.sum(axis=0))
print('전체 표준편차: ', round(arr2.std(),2))


In [ ]:
# 문제:
# 아래 데이터를 사용해 Matplotlib의 plot() 함수로 선 그래프를 그려보세요.

# ✅ 조건:

# 파란색 실선('-')

# 원형 마커('o')

# 선 두께 2

# 마커 크기 8

# 격자(grid) 추가

# ✅ 데이터:

# x = [0, 1, 2, 3, 4]
# y = [2, 5, 3, 8, 7]
# ✅ 예시 출력:

# 파란 실선, 큰 원형 마커, 그리드가 켜진 깔끔한 선 그래프

import matplotlib.pyplot as plt

x = [0, 1, 2, 3, 4]
y = [2, 5, 3, 8, 7]

plt.grid()
plt.plot(x, y, 'bo-', linewidth=2, markeredgewidth=8)



In [ ]:
# ✅ 문제 2 (중간 ⭐⭐⭐)
# 문제:
# Matplotlib의 subplot을 이용해 하나의 figure에 2개의 그래프를 배치해보세요.

# ✅ 조건:

# 위쪽 subplot(211): 빨간색 실선('-')

# 아래쪽 subplot(212): 초록색 점선(':')

# 두 그래프 모두 X-Axis, Y-Axis 라벨 추가

# 두 그래프 모두 grid() 켜기 (linestyle='--', color='gray', alpha=0.5)

# ✅ 데이터:

# x = [1, 2, 3, 4]
# y1 = [10, 20, 15, 25]
# y2 = [8, 17, 14, 20]
# ✅ 예시 출력:

# 하나의 figure에서 위아래로 2개의 다른 스타일 그래프
import matplotlib.pyplot as plt

x = [1, 2, 3, 4]
y1 = [10, 20, 15, 25]
y2 = [8, 17, 14, 20]

plt.figure(1)
plt.subplot(211)

plt.grid(linestyle='--', color='gray', alpha=0.5)
plt.plot(x, y1, 'r-')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')

plt.subplot(212)
plt.grid(linestyle='--', color='gray', alpha=0.5)
plt.plot(x, y2 , 'g:')
plt.xlabel('X-Axis')
plt.ylabel('Y-Axis')





In [ ]:
# ✅ 문제 3 (중간 ⭐⭐⭐)
# 문제:
# 아래 데이터를 가지고 색상 조건을 넣은 막대 그래프를 그리세요.

# ✅ 조건:

# 양수 값: 파란색

# 음수 값: 빨간색

# plt.bar() 사용

# ✅ 데이터:
# x = np.arange(5)
# val = [10, -5, 12, -8, 7]
# ✅ 예시 출력:

# 양수 막대는 파란색, 음수 막대는 빨간색
import matplotlib.pyplot as plt
x = np.arange(5)
val = [10, -5, 12, -8, 7]

colors = ['blue' if v >= 0 else 'red' for v in val]
plt.bar(x, val, color=colors)



In [ ]:
# ✅ 문제 4 (어려움 ⭐⭐⭐⭐)
# 문제:
# Matplotlib의 pie() 함수를 사용해 아래 조건을 만족하는 원형 차트를 그리세요.

# ✅ 조건:

# 데이터: [30, 20, 25, 25]

# 각 조각 색상: ['red','blue','green','orange']

# 두 번째 조각만 살짝 튀어나오게 (explode=0.1)

# 제목(title) 추가

# ✅ 예시 출력:

# 색상별로 구분된 예쁜 파이차트

import matplotlib.pyplot as plt


x = [30, 20, 25, 25]
col = ['red','blue','green','orange']
exp = [0.0,0.1,0.0,0.0]
plt.title('pie')
plt.pie(x, colors=col, explode=exp)